#!/usr/bin/env node
/**
 * commit-bot.js
 * Автономный «бот-коммитер» для фронтенд-репозитория.
 * - Каждые 8–16 часов (рандом) делает один коммит и пуш.
 * - В каждом цикле правит 2–4 файла из набора целей (components, utils, styles, README, package.json, .eslintrc.json, tests).
 * - Сообщения в стиле Conventional Commits + телο со списком изменений.
 * - Не требует сторонних npm-пакетов.
 *
 * РЕКОМЕНДАЦИЯ: держать репозиторий приватным.
 */

const { execSync } = require("child_process")
const fs = require("fs")
const path = require("path")

//// ------------------------ CONFIG ------------------------
const MIN_HOURS = 8
const MAX_HOURS = 16
const REPO_ROOT = process.cwd()

// если хочешь фикс. расписание, можно заменить на константу в миллисекундах
function nextDelayMs() {
  const h = MIN_HOURS + Math.random() * (MAX_HOURS - MIN_HOURS)
  return Math.round(h * 60 * 60 * 1000)
}

const AUTHOR_NAME = null // например "Frontend Bot"
const AUTHOR_EMAIL = null // например "bot@example.com"
// Если задать оба значения — будет использоваться --author. Если нет — возьмёт обычные git-конфиги пользователя.

//// ------------------------ UTILS ------------------------
function run(cmd, opts = {}) {
  try {
    return execSync(cmd, { cwd: REPO_ROOT, stdio: "pipe", encoding: "utf8", ...opts }).trim()
  } catch (e) {
    throw new Error(`Command failed: ${cmd}\n${e.message || e}`)
  }
}

function ensureDir(p) {
  if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true })
}

function randomFrom(arr) {
  return arr[Math.floor(Math.random() * arr.length)]
}

function nowISO() {
  return new Date().toISOString()
}

function log(msg) {
  const line = `[${new Date().toLocaleString()}] ${msg}\n`
  process.stdout.write(line)
  try {
    ensureDir(path.join(REPO_ROOT, "logs"))
    fs.appendFileSync(path.join(REPO_ROOT, "logs", "commit-bot.log"), line)
  } catch (_) {}
}

//// ------------------------ PROJECT SCaffold ------------------------
function ensureProjectScaffold() {
  ensureDir(path.join(REPO_ROOT, "src", "components"))
  ensureDir(path.join(REPO_ROOT, "src", "utils"))
  ensureDir(path.join(REPO_ROOT, "src", "styles"))
  ensureDir(path.join(REPO_ROOT, "tests"))

  const gitignore = path.join(REPO_ROOT, ".gitignore")
  if (!fs.existsSync(gitignore)) {
    fs.writeFileSync(gitignore, "node_modules/\nlogs/\n.DS_Store\n", "utf8")
  }

  const readme = path.join(REPO_ROOT, "README.md")
  if (!fs.existsSync(readme)) {
    fs.writeFileSync(readme, `# ${path.basename(REPO_ROOT)}\n\nAuto-maintained repo.\n\n`, "utf8")
  }

  const pkg = path.join(REPO_ROOT, "package.json")
  if (!fs.existsSync(pkg)) {
    const pkgJson = {
      name: path
        .basename(REPO_ROOT)
        .toLowerCase()
        .replace(/[^a-z0-9-_.]/g, "-"),
      private: true,
      version: "0.0.1",
      description: "Auto-maintained demo project",
      scripts: {
        dev: "echo dev",
        test: "node tests/run.js || true",
      },
    }
    fs.writeFileSync(pkg, JSON.stringify(pkgJson, null, 2) + "\n", "utf8")
  }

  const eslint = path.join(REPO_ROOT, ".eslintrc.json")
  if (!fs.existsSync(eslint)) {
    fs.writeFileSync(
      eslint,
      JSON.stringify(
        {
          env: { es2021: true, browser: true, node: true },
          extends: [],
          rules: { "no-unused-vars": "warn", "no-undef": "error" },
        },
        null,
        2
      ) + "\n",
      "utf8"
    )
  }

  const testRunner = path.join(REPO_ROOT, "tests", "run.js")
  if (!fs.existsSync(testRunner)) {
    fs.writeFileSync(
      testRunner,
      `// naive test runner placeholder\nconst assert = require('assert');\nconsole.log('Tests OK at', new Date().toISOString());\n`,
      "utf8"
    )
  }
}

//// ------------------------ CHANGE GENERATORS ------------------------
function addOrUpdateComponent(changes) {
  const dir = path.join(REPO_ROOT, "src", "components")
  ensureDir(dir)
  const baseNames = [
    "Header",
    "Footer",
    "Card",
    "Modal",
    "Sidebar",
    "Widget",
    "Badge",
    "Toolbar",
    "List",
    "Avatar",
  ]
  const createNew = Math.random() < 0.6

  if (createNew || !fs.readdirSync(dir).some((f) => f.endsWith(".jsx"))) {
    const name = randomFrom(baseNames) + Math.floor(Math.random() * 10000)
    const file = path.join(dir, `${name}.jsx`)
    const content = `// ${name} — autogenerated ${nowISO()}\nimport React from 'react';\n\nexport default function ${name}(){\n  return (\n    <div className="${name.toLowerCase()}">\n      <h3>${name}</h3>\n    </div>\n  );\n}\n`
    fs.writeFileSync(file, content, "utf8")
    changes.push({ type: "feat", scope: "ui", description: `add ${name} component`, file })
  } else {
    // обновим существующий компонент — добавим маленький проп
    const files = fs.readdirSync(dir).filter((f) => f.endsWith(".jsx"))
    const pick = path.join(dir, randomFrom(files))
    let code = fs.readFileSync(pick, "utf8")
    if (!code.includes("/* updated */")) {
      code = code.replace(
        /export default function ([^(]+)\(\)\s*{/,
        (m, comp) =>
          `export default function ${comp}({ title = "${path.basename(pick, ".jsx")}" }) {`
      )
      code = code.replace(
        /<\/div>\s*\);\s*}\s*$/,
        `      {/* updated ${nowISO()} */}\n      {title ? <p>{title}</p> : null}\n    </div>\n  );\n}\n`
      )
      fs.writeFileSync(pick, code, "utf8")
      changes.push({
        type: "refactor",
        scope: "ui",
        description: `tweak ${path.basename(pick)} props`,
        file: pick,
      })
    }
  }
}

function touchUtils(changes) {
  const dir = path.join(REPO_ROOT, "src", "utils")
  ensureDir(dir)
  const file = path.join(dir, "date.js")
  let content
  if (!fs.existsSync(file)) {
    content = `// utils/date — autogenerated ${nowISO()}\nexport function formatISO(dt=new Date()){return dt.toISOString();}\nexport function toLocale(dt=new Date()){return dt.toLocaleString();}\n`
    fs.writeFileSync(file, content, "utf8")
    changes.push({ type: "feat", scope: "utils", description: "add date utils", file })
  } else {
    content = fs.readFileSync(file, "utf8")
    if (!content.includes("addDays")) {
      content += `\nexport function addDays(d=new Date(), n=1){const x=new Date(d);x.setDate(x.getDate()+n);return x;}\n`
      fs.writeFileSync(file, content, "utf8")
      changes.push({
        type: "feat",
        scope: "utils",
        description: "extend date utils (addDays)",
        file,
      })
    } else {
      content = content.replace(
        "return dt.toISOString();",
        "return new Date(dt).toISOString(); // normalized"
      )
      fs.writeFileSync(file, content, "utf8")
      changes.push({ type: "refactor", scope: "utils", description: "normalize formatISO", file })
    }
  }
}

function touchStyles(changes) {
  const dir = path.join(REPO_ROOT, "src", "styles")
  ensureDir(dir)
  const file = path.join(dir, "main.css")
  let css = fs.existsSync(file)
    ? fs.readFileSync(file, "utf8")
    : `/* styles/main.css */\n:root{--gap:8px}\n`
  css += `\n/* tick ${nowISO()} */\n.container{padding:var(--gap)}\n`
  fs.writeFileSync(file, css, "utf8")
  changes.push({
    type: "style",
    scope: "styles",
    description: "adjust spacing and container padding",
    file,
  })
}

function touchReadme(changes) {
  const file = path.join(REPO_ROOT, "README.md")
  const stamp = nowISO()
  const note = `\n## Changelog\n- ${stamp}: maintenance, minor improvements\n`
  let content = fs.existsSync(file)
    ? fs.readFileSync(file, "utf8")
    : `# ${path.basename(REPO_ROOT)}\n`
  if (!content.includes("## Changelog")) content += note
  else
    content = content.replace(
      /## Changelog[\s\S]*$/m,
      (m) => `${m}\n- ${stamp}: maintenance, minor improvements`
    )
  fs.writeFileSync(file, content, "utf8")
  changes.push({ type: "docs", scope: "readme", description: "update changelog", file })
}

function bumpPackageJson(changes) {
  const file = path.join(REPO_ROOT, "package.json")
  if (!fs.existsSync(file)) return
  const pkg = JSON.parse(fs.readFileSync(file, "utf8"))
  const [maj, min, pat] = (pkg.version || "0.0.0").split(".").map((n) => parseInt(n || 0, 10))
  pkg.version = `${maj}.${min}.${(pat || 0) + 1}`
  if (!pkg.description) pkg.description = "Auto-maintained demo project"
  fs.writeFileSync(file, JSON.stringify(pkg, null, 2) + "\n", "utf8")
  changes.push({
    type: "chore",
    scope: "release",
    description: `bump version to ${pkg.version}`,
    file,
  })
}

function tweakEslint(changes) {
  const file = path.join(REPO_ROOT, ".eslintrc.json")
  if (!fs.existsSync(file)) return
  const cfg = JSON.parse(fs.readFileSync(file, "utf8"))
  cfg.rules = cfg.rules || {}
  // лёгкая правка: добавить rule eqeqeq или поменять уровень
  cfg.rules.eqeqeq = cfg.rules.eqeqeq === "warn" ? "error" : "warn"
  fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + "\n", "utf8")
  changes.push({ type: "chore", scope: "lint", description: "tune eslint eqeqeq", file })
}

function addTest(changes) {
  const dir = path.join(REPO_ROOT, "tests")
  ensureDir(dir)
  const name = `utils_${Date.now()}.test.js`
  const file = path.join(dir, name)
  const body = `// autogenerated ${nowISO()}\nconst assert = require('assert');\nassert.strictEqual(1+1,2);\nconsole.log('ok: ${name}');\n`
  fs.writeFileSync(file, body, "utf8")
  changes.push({ type: "test", scope: "utils", description: `add ${name}`, file })
}

//// ------------------------ GIT OPS ------------------------
function currentBranch() {
  try {
    return run("git rev-parse --abbrev-ref HEAD") || "main"
  } catch {
    return "main"
  }
}

function gitPullRebase() {
  try {
    run("git pull --rebase --autostash")
    log("git pull --rebase: OK")
  } catch (e) {
    log("git pull --rebase: " + e.message)
  }
}

function gitCommitAndPush(changes) {
  if (!changes.length) {
    log("No changes to commit.")
    return false
  }

  // Сводная «шапка» коммита по первой важной операции
  const primary = changes.find((c) => c.type === "feat") || changes[0]
  const header = `${primary.type}(${primary.scope}): ${primary.description}`

  // Тело коммита: маркированный список всех изменений
  const body =
    "\n\n" +
    changes
      .map(
        (c) =>
          `- ${c.type}(${c.scope}): ${c.description}${
            c.file ? ` (${path.relative(REPO_ROOT, c.file)})` : ""
          }`
      )
      .join("\n")

  // Автор (опционально)
  const authorFlag =
    AUTHOR_NAME && AUTHOR_EMAIL ? ` --author="${AUTHOR_NAME} <${AUTHOR_EMAIL}>"` : ""

  try {
    run("git add -A")
    run(
      `git commit -m "${header.replace(/"/g, '\\"')}" -m "${body.replace(
        /"/g,
        '\\"'
      )}"${authorFlag}`
    )
  } catch (e) {
    if (String(e.message).includes("nothing to commit")) {
      log("Nothing to commit.")
      return false
    }
    throw e
  }

  try {
    run("git push")
    log(`Pushed: ${header}`)
    return true
  } catch (e) {
    log("git push failed: " + e.message)
    return false
  }
}

//// ------------------------ MAIN CYCLE ------------------------
function performChangeCycle() {
  ensureProjectScaffold()
  gitPullRebase()

  const generators = [
    addOrUpdateComponent,
    touchUtils,
    touchStyles,
    touchReadme,
    bumpPackageJson,
    tweakEslint,
    addTest,
  ]

  // Выберем 2–4 уникальные операции на цикл
  const count = 2 + Math.floor(Math.random() * 3) // 2..4
  const pick = []
  const pool = generators.slice()
  for (let i = 0; i < count && pool.length; i++) {
    const idx = Math.floor(Math.random() * pool.length)
    pick.push(pool.splice(idx, 1)[0])
  }

  const changes = []
  for (const gen of pick) {
    try {
      gen(changes)
    } catch (e) {
      log(`Generator error: ${e.message}`)
    }
  }

  gitCommitAndPush(changes)
}

async function sleep(ms) {
  await new Promise((res) => setTimeout(res, ms))
}

async function loopForever() {
  log(`Commit-bot started on branch "${currentBranch()}". Repo: ${REPO_ROOT}`)
  for (;;) {
    try {
      performChangeCycle()
    } catch (e) {
      log("Cycle error: " + e.message)
    }
    const delay = nextDelayMs()
    const hours = Math.round((delay / 36e5) * 10) / 10
    log(`Next run in ~${hours}h`)
    await sleep(delay)
  }
}

loopForever().catch((e) => {
  log("Fatal error: " + e.message)
  process.exit(1)
})
